In [1]:
import pandas as pd

## loading the master dataset

In [2]:
df = pd.read_csv("../data/cleaned/master_dataset.csv")

In [4]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,40.0,268.0,4.0,500.0,19.0,8.0,13.0,9350.0,maua,SP
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,29.0,178.0,1.0,400.0,19.0,13.0,19.0,31570.0,belo horizonte,SP
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,46.0,232.0,1.0,420.0,24.0,19.0,21.0,14840.0,guariba,SP

In [5]:
df.shape

(118434, 33)

In [6]:
df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 118434 entries, 0 to 118433
Data columns (total 33 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       118434 non-null  str
 1   customer_id                    118434 non-null  str
 2   order_status                   118434 non-null  str
 3   order_purchase_timestamp       118434 non-null  str
 4   order_approved_at              118258 non-null  str
 5   order_delivered_carrier_date   116360 non-null  str
 6   order_delivered_customer_date  115037 non-null  str
 7   order_estimated_delivery_date  118434 non-null  str
 8   customer_unique_id             118434 non-null  str
 9   customer_zip_code_prefix       118434 non-null  int64
 10  customer_city                  118434 non-null  str
 11  customer_state                 118434 non-null  str
 12  order_item_id                  117604 non-null  float64
 13  product_id                     117604 non-null  str
 14  seller_id                      117604 non-null  str
 15  shipping_limit_date            117604 non-null  str
 16  price                          117604 non-null  float64
 17  freight_value                  117604 non-null  float64
 18  payment_sequential             118431 non-null  float64
 19  payment_type                   118431 non-null  str
 20  payment_installments           118431 non-null  float64
 21  payment_value                  118431 non-null  float64
 22  product_category_name          115906 non-null  str
 23  product_name_lenght            115906 non-null  float64
 24  product_description_lenght     115906 non-null  float64
 25  product_photos_qty             115906 non-null  float64
 26  product_weight_g               117584 non-null  float64
 27  product_length_cm              117584 non-null  float64
 28  product_height_cm              117584 non-null  float64
 29  product_width_cm               117584 non-null  float64
 30  seller_zip_code_prefix         117604 non-null  float64
 31  seller_city                    117604 non-null  str
 32  seller_state                   117604 non-null  str
dtypes: float64(14), int64(1), str(18)
memory usage: 29.8 MB

In [9]:
df.isna().sum().sort_values(ascending=False)

order_delivered_customer_date    3397
product_photos_qty               2528
product_description_lenght       2528
product_name_lenght              2528
product_category_name            2528
order_delivered_carrier_date     2074
product_width_cm                  850
product_height_cm                 850
product_length_cm                 850
product_weight_g                  850
price                             830
shipping_limit_date               830
seller_city                       830
seller_zip_code_prefix            830
freight_value                     830
seller_state                      830
product_id                        830
order_item_id                     830
seller_id                         830
order_approved_at                 176
payment_sequential                  3
payment_type                        3
payment_installments                3
payment_value                       3
customer_id                         0
order_estimated_delivery_date       0
order_status                        0
order_purchase_timestamp            0
customer_state                      0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
order_id                            0
dtype: int64

In [13]:
## null values in percentage

In [14]:
(df.isna().sum() / len(df) * 100).sort_values(ascending= False)

order_delivered_customer_date    2.868264
product_photos_qty               2.134522
product_description_lenght       2.134522
product_name_lenght              2.134522
product_category_name            2.134522
order_delivered_carrier_date     1.751186
product_width_cm                 0.717699
product_height_cm                0.717699
product_length_cm                0.717699
product_weight_g                 0.717699
price                            0.700812
shipping_limit_date              0.700812
seller_city                      0.700812
seller_zip_code_prefix           0.700812
freight_value                    0.700812
seller_state                     0.700812
product_id                       0.700812
order_item_id                    0.700812
seller_id                        0.700812
order_approved_at                0.148606
payment_sequential               0.002533
payment_type                     0.002533
payment_installments             0.002533
payment_value                    0.002533
customer_id                      0.000000
order_estimated_delivery_date    0.000000
order_status                     0.000000
order_purchase_timestamp         0.000000
customer_state                   0.000000
customer_unique_id               0.000000
customer_zip_code_prefix         0.000000
customer_city                    0.000000
order_id                         0.000000
dtype: float64

In [15]:
# missing product category label to "unknown"

In [16]:
df["product_category_name"] = df["product_category_name"].fillna("unknown")

In [17]:
# important ids are also missing , so dropping those

In [19]:
df = df.dropna(subset=["order_id","seller_id","customer_id"])

In [20]:
# date column formats

In [24]:
df["order_purchase_timestamp"] = pd.to_datetime(df["order_purchase_timestamp"])
df["order_delivered_customer_date"] = pd.to_datetime(df["order_delivered_customer_date"])

In [25]:
# feature engineering

In [26]:
df["total_value"] = df["price"] + df["freight_value"]

In [27]:
df["delivery_time_days"] = (
    df["order_delivered_customer_date"] - df["order_purchase_timestamp"]
).dt.days

In [34]:
# month extraction
df["order_month"]=df["order_purchase_timestamp"].dt.to_period("M")
df["order_month"]

0         2017-10
1         2017-10
2         2017-10
3         2018-07
4         2018-08
           ...
118429    2018-02
118430    2017-08
118431    2018-01
118432    2018-01
118433    2018-03
Name: order_month, Length: 117604, dtype: period[M]

In [35]:
df["order_year"] = df["order_purchase_timestamp"].dt.year
df["order_year"]

0         2017
1         2017
2         2017
3         2018
4         2018
          ...
118429    2018
118430    2017
118431    2018
118432    2018
118433    2018
Name: order_year, Length: 117604, dtype: int32

In [36]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,total_value,delivery_time_days,order_month,order_year
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,19.0,8.0,13.0,9350.0,maua,SP,38.71,8.0,2017-10,2017
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,19.0,8.0,13.0,9350.0,maua,SP,38.71,8.0,2017-10,2017
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,19.0,8.0,13.0,9350.0,maua,SP,38.71,8.0,2017-10,2017
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,19.0,13.0,19.0,31570.0,belo horizonte,SP,141.46,13.0,2018-07,2018
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,24.0,19.0,21.0,14840.0,guariba,SP,179.12,9.0,2018-08,2018

In [39]:
# saving the cleaned dataset
df.to_csv("../data/cleaned/analytics-dataset.csv",index=False)